language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

go_import_path: github.com/gpucloud/node-topology-manager

# let us have speedy Docker-based Travis workers
sudo: false

script:
  - go build cmd/*.go
  - go vet ./...
  - go test ./...
